# Generated by Django 4.2.1 on 2023-06-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('gu', models.CharField(max_length=15)),
                ('longitude', models.EmailField(max_length=254)),
                ('latitude', models.CharField(max_length=100)),
            ],
        ),
    ]
