# Generated by Django 4.2.1 on 2023-06-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='police',
            old_name='user_id',
            new_name='code',
        ),
    ]
