# Generated by Django 4.2.1 on 2023-06-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_user_id_police_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='police',
            name='longitude',
        ),
    ]
