# Generated by Django 4.2.1 on 2023-06-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_police_latitude_remove_police_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='police',
        ),
    ]
